-- superseded by migrations/20260827_reports_moderation.sql and
-- migrations/20260927_admin_hardening.sql.
-- Do not re-run this file: the previous policies compared reporter_id (text)
-- to auth.uid() (uuid) and would fail, and they also allowed a username
-- fallback (sgurzheyev) instead of profiles.role via public.is_admin().
